#!/bin/sh

case "$1" in
  start)
        sudo -u tomcat7 /ibi/srv80/wfs/bin/edastart -start
        ;;
  restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
  stop)
        sudo -u tomcat7 /ibi/srv80/wfs/bin/edastart -stop 
        ;;
  *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac

:
