#!/bin/sh

case "$1" in
  start)
        echo "nohup /ibi/derby/bin/start.sh > /ibi/derby/log/process.log" > /tmp/tmp.sh
        sudo chmod 777 /tmp/tmp.sh
        sudo -u tomcat7 /tmp/tmp.sh &
        ;;
  restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
  stop)
        sudo -u tomcat7 /ibi/derby/bin/stop.sh
        ;;
  *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac

:
